name: Run Unit Tests

inputs:
  component:
    description: The name of the component to test
    required: false
  args:
    description: Additional options
    required: false

runs:
  using: composite
  steps:
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: ./yarn.lock
    - name: Install & run tests
      shell: bash
      run: |
        yarn install --frozen-lockfile
        yarn test --silent --hideSkippedTests --run ${{ inputs.component }} ${{ inputs.args }}
