name: Run Unit Tests

inputs:
  component:
    required: false
  exclusion:
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: ./yarn.lock
    - shell: bash
      run: |
        yarn install --frozen-lockfile

        if [ -n "${{ inputs.exclusion }}" ]; then
          yarn test --silent --hideSkippedTests --run --exclude '${{ inputs.exclusion }}'
        else
          yarn test --silent --hideSkippedTests --run ${{ inputs.component }}
        fi
