name: Get Environment Name
description: Parse github context and return an environment name

outputs:
  env:
    description: Environment name
    value: ${{ steps.getEnv.outputs.env }}

runs:
  using: composite
  steps:
    - id: getEnv
      shell: bash
      run: |
        if [[ '${{ github.event_name }}' == 'push' || '${{ github.event_name }}' == 'workflow_dispatch' ]]; then
          base_branch=${{ github.ref_name }}
        elif [[ '${{ github.event_name }}' == 'pull_request' ]]; then
          base_branch=${{ github.event.pull_request.base.ref }}
        else
          echo 'Unsupported event for this action'
          exit 1
        fi

        if [[ $base_branch == 'develop' ]]; then
          env=dev
        elif [[ $base_branch == release/* ]]; then
          env=test
        elif [[ $base_branch == hotfix/* ]]; then
          env=staging
        else
          exit 1
        fi

        prefix='yom-'
        echo 'env=$prefix$env' >> $GITHUB_OUTPUT
