name: deploy

on:
  push:
    branches:
      - develop
      - 'release/**'
      - 'hotfix/**'
  workflow_call:
    inputs:
      environment_name:
        type: string
        required: true

jobs:
  get-env:
    if: github.event_name != 'workflow_call'
    name: Get environment name
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.getEnv.outputs.env }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4
      - id: getEnv
        uses: ./.github/actions/get-env

  build:
    needs: get-env
    name: Build & deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name || needs.get-env.outputs.env }}
    timeout-minutes: 7
    env:
      APP: ${{ vars.APP }}
      ENV: ${{ vars.ENV }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/unit-tests
        continue-on-error: false
      - name: Compile
        run: yarn build
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4

  notify:
    name: Notify Slack channel
    needs: build
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set variables
        id: vars
        run: |
          {
            sha_short=$(git rev-parse --short HEAD)
            echo "sha_short=$sha_short"
            echo "subject=$(git log --format=%s -n 1 HEAD)"

            if [ "${{ needs.build.result }}" == "success" ]; then
              echo "status_icon=:white_check_mark:"
              echo "status_text=succeeded"
            else
              echo "status_icon=:no_entry:"
              echo "status_text=failed"
            fi

            if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              echo "commit_url=${{ github.event.repository.html_url }}/commit/$sha_short"
              echo "actor=${{ github.triggering_actor }}"
            else
              echo "commit_url=${{ github.event.head_commit.url }}"
              echo "actor=${{ github.actor }}"
            fi
          } >> $GITHUB_OUTPUT

      - name: Notify Slack channel
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: D01NHJ9QV51 # yom private DM
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.vars.outputs.status_icon }} <${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} #${{ github.run_number}}> *${{ steps.vars.outputs.status_text }}*."
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "> <${{ steps.vars.outputs.commit_url }}|`${{ steps.vars.outputs.sha_short }}`> ${{ steps.vars.outputs.subject }}\n> by *${{ steps.vars.outputs.actor }}*"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_FE_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
