name: Validations
on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          base_branch=${{ github.base_ref }}

          if [[ $base_branch == 'develop' ]]; then
            env=dev
          elif [[ $base_branch == release/* ]]; then
            env=test
          elif [[ $base_branch == hotfix/* ]]; then
            env=staging
          elif [[ $base_branch == 'feat' ]]; then
            env=feat
          fi
      - name: Validations
        uses: ./.github/actions/validations