name: Required Checks

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
          cache-dependency-path: ./yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: npm run test:unit
  
  deploy:
    uses: ./.github/workflows/deploy.yaml
    # secrets: inheritgit pu