name: Unit tests

on:
  push:
  # pull_request:
  #   types: [synchronize, opened, reopened]
    branches-ignore:
      - somebranch-*

jobs:
  get-env:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.getEnv.outputs.env }}
    steps:
      - uses: actions/checkout@v4
      - id: getEnv
        uses: ./.github/actions/get-env
        with:
          prefix: 'yom-'

  test:
    needs: get-env
    runs-on: ubuntu-latest
    environment: ${{ needs.get-env.outputs.env  }}
    env:
      APP: ${{ vars.APP }}
      ENV: ${{ vars.ENV }}
      NPM_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        component:
          - Dashboard
          - Reports
          - Account
          - Common
          - Organization
        include:
          - component: Organization
            # needs to be whitespace-delimited
            alt: organisation
          - component: Common
            exclude: '{**/dashboard/**,**/reports/**,**/account/**}'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/unit-tests
        with:
          component: ${{ matrix.component }} ${{ matrix.alt }}
          exclusion: ${{ matrix.exclude }}
