name: Validations
on:
  pull_request:
  push:
    # branches:
    #   - JWC-*
    #   - jwc-*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "OTONG=123"
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      - name: Validations
        uses: ./.github/actions/validations