name: Validations
on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validations
        uses: ./.github/actions/validations
        with:
          env: ${{ steps.getEnv.outputs.env }}