name: Unit tests

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches-ignore:
      - msteams-*

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP: yom-app
      ENV: yom-de
      NPM_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        component:
          - Dashboard
          - Reports
          - Account
          - Common
          - Organization
        include:
          - component: Organization
            # needs to be whitespace-delimited
            alt: organisation
          - component: Common
            exclude: '{**/dashboard/**,**/reports/**,**/account/**}'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/unit-tests
        with:
          component: ${{ matrix.component }} ${{ matrix.alt }}
          exclusion: ${{ matrix.exclude }}
