name: Unit tests

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches-ignore:
      - msteams-*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP: yom-app
      ENV: yom-dev
      NPM_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        component:
          - Dashboard
          - Reports
          - Account
          - Common
          - Organization
        include:
          - component: Organization
            alt: organisation
          - component: Common
            args: "--exclude='{**/dashboard/**,**/reports/**,**/account/**}'"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/unit-tests
        with:
          component: ${{ matrix.component }} ${{ matrix.alt }}
          args: ${{ matrix.args }}
