name: req-check

on: [workflow_call]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: |
          echo "Node $(node -v)"
          yarn
          yarn test:unit